name: Test application

on:
  workflow_dispatch:
    inputs:
      TEST_TYPE:
        required: false
        type: string
        default: acceptance
        description: Either 'unit' or 'acceptance' or 'cypress'

permissions: write-all

jobs:
  call-build:
    if: ${{inputs.TEST_TYPE == 'unit'}}
    uses: trevorism/actions-workflows/.github/workflows/build.yml@master
    with:
      JDK_VERSION: 17

  call-accept:
    if: ${{inputs.TEST_TYPE == 'acceptance'}}
    uses: trevorism/actions-workflows/.github/workflows/accept.yml@master
    with:
      JDK_VERSION: 17

  call-cypress:
    if: ${{inputs.TEST_TYPE == 'cypress'}}
    uses: trevorism/actions-workflows/.github/workflows/cypress.yml@master